### ISSUE TITLE
Periodic error: Assertion ctx failed in evmap_io_active

### ISSUE THREAD

**Issue by ownport** [ownport/pyactors#55]
```
Running tests
...............................[err] evmap.c:401: Assertion ctx failed in evmap_io_active
F..................................
======================================================================
FAIL: test_forked_greenlet_actors.test_processing_with_diff_timelife_children
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/data/devel/virtenvs/pyactors/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/media/data/devel/virtenvs/pyactors/pyactors/tests/test_forked_greenlet_actors.py", line 214, in test_processing_with_diff_timelife_children
    assert len(result) == 10, result
AssertionError: ['imap_job:Child-3:2', 'imap_job:Child-2:1', 'imap_job:Child-1:0', 'imap_job:Child-3:0', 'imap_job:Child-3:1', 'imap_job:Child-2:0']
```

**Comment by ownport** [comment]
the same error raised for `test_forked_greenlet_actors.test_processing_with_diff_timelife_children`

**Comment by ownport** [comment]
forked generator and greenlet actors are deprecated

**Comment by ownport** [comment]
see branch `new-actor-flow`
